const base = import.meta.env.BASE_URL;
const asset = (name) => `${base}figma/${name}`;
const img = (name, alt = '', cls = '', eager = false) => `<img src="${asset(name)}" alt="${alt}" class="${cls}" loading="${eager ? 'eager' : 'lazy'}" decoding="async" />`;
const urls = { transfers: 'https://www.jiffy.com/transfers', blanks: 'https://www.jiffy.com/', gang: 'https://www.jiffy.com/jiffytransfers-DTFGANG001.html' };
const brand = () => `<div class="local-brand"><div><p>Jiffy Local</p><span class="yellow-rule"></span></div><span>DALLAS-FORT WORTH</span></div>`;
const products = [
  { brand: 'GILDAN · G800', title: 'Heavy Cotton™ T-Shirt (White)', price: '2.59' },
  { brand: 'GILDAN · G800', title: 'Heavy Cotton™ T-Shirt (Black)', price: '2.59' },
  { brand: 'GILDAN · G185', title: 'Heavy Blend® Hoodie (Grey)', price: '9.76' },
  { brand: 'GILDAN · G185', title: 'Heavy Blend® Crewneck (Black)', price: '11.35' },
];
function productRow(offset = 0) {
  return `<div class="product-row">${products.map((p, i) => `<a class="product-card" href="${urls.blanks}" data-shop="blanks" aria-label="Shop ${p.title}"><div class="product-photo">${img(`product-image${i + offset || ''}.png`, p.title)}</div><div class="product-info"><p class="product-brand">${p.brand}</p><h3 title="${p.title}">${p.title}</h3><p class="product-price">from <strong>$${p.price}</strong></p><div class="reviews">${img('group4.svg', '4 out of 5 stars')}<span>(2,500)</span></div></div></a>`).join('')}</div>`;
}
function addressForm(id, hero = false) {
  return `<form class="address-form ${hero ? 'hero-address' : ''}" data-address-form><div class="address-input-row"><label for="${id}" class="sr-only">Delivery address</label>${img('icons.svg', '', 'location-icon', true)}<input id="${id}" name="address" type="text" autocomplete="street-address" placeholder="Enter your delivery address" required /><button class="button yellow" type="submit">${hero ? 'Check you delivery time' : 'Check delivery time'}</button></div><p class="address-status" role="status" hidden></p></form>`;
}
const features = [
  ['exec-e59462-f1-d28-e4-a95-ad478641157-b2-d8-c1.png', 'Vibrant color', 'Rich, consistent colors that last.'],
  ['exec9157-ce347-a494-e0-d88-d6-dadc260-f445-f1.png', 'Crisp detail', 'Prints fine lines and complex artwork.'],
  ['exec6-edb0-d4736754193-a9-f97-a1-d4-e14180-a1.png', 'Clean peel', 'Hot or cold peel. No hassle.'],
  ['exec8-f8-b18-e3-fd534-ca286-c5-ca34446891-c31.png', 'Fast processing', 'Printed and ready for local delivery.'],
];
const transferTypes = [['ProColor', 'Color made to hold up.'], ['Glitter', 'A little more shine.'], ['Glow-in-the-Dark', 'Made to stand out.'], ['Reflective', 'Catch the light.'], ['Gold Foil', 'Bring the finish.']];

document.querySelector('#app').innerHTML = `
  <section class="chapter hero" id="hero" aria-labelledby="hero-title"><div class="hero-photo">${img('property1-frame77.png', 'Dallas–Fort Worth creators wearing printed apparel', '', true)}</div><header class="hero-nav"><a href="#hero" aria-label="Jiffy home">${img('link-jiffy-com-svg.svg', 'Jiffy', 'jiffy-logo', true)}</a><a class="button outline" href="https://www.jiffy.com/login">Sign in</a></header><div class="hero-panel"><div class="hero-copy"><h1 id="hero-title">DTF Transfers +  Blank apparel,  delivery in hours.</h1><p>Enter your address to see what’s available and when it can arrive.</p></div>${addressForm('hero-address', true)}</div></section>
  <section class="chapter transfers" id="transfers" aria-labelledby="transfers-title"><header class="transfer-heading">${brand()}<h2 id="transfers-title">Your design. Our quality<span class="dot">.</span></h2><p>Upload your artwork, then choose the transfer path that fits your project.</p></header><div class="catalog-body"><div class="upload-panel" id="upload-panel"><div class="upload-intro">${img('cloud-upload.svg', '', 'upload-icon')}<div><h3>Upload your artwork</h3><p>PNG, JPG, PDF (300 DPI recommended)</p></div></div><div class="upload-actions"><button class="button navy" id="choose-file" type="button">Choose file</button><input id="artwork" class="sr-only" type="file" accept="image/png,image/jpeg,application/pdf" tabindex="-1" /><div class="upload-or"><span></span>OR<span></span></div><a class="templates-link" href="${urls.transfers}" data-shop="transfers">Browse design templates →</a></div><p class="upload-status" role="status" hidden></p></div><div class="catalog-products"><div class="artwork-paths"><h3>Start with your artwork</h3><div class="transfer-cards"><a class="transfer-card" href="${urls.transfers}" data-shop="transfers"><div class="transfer-art by-size">${img('image50.png', 'Colorful DTF design')}</div><div class="transfer-card-copy"><h4>DTF Transfers by size</h4><p>Upload a design and choose the size.</p><div class="transfer-price"><strong>From $0.06 / sq. in.</strong>${img('arrow-forward.svg')}</div></div></a><a class="transfer-card" href="${urls.gang}" data-shop="gang"><div class="transfer-art gang">${img('image51.png', '')}${img('image52.png', 'Multiple designs arranged on a gang sheet')}</div><div class="transfer-card-copy"><h4>Gang sheet- DTF transfers</h4><p>Arrange multiple designs on one sheet.</p><div class="transfer-price"><strong>From $11.59 / foot</strong>${img('arrow-forward.svg')}</div></div></a></div></div><hr />${productRow()}</div></div><div class="transfer-quality-inline"><header><p class="eyebrow">⚡ PROFESSIONAL QUALITY. LOCALLY DELIVERED.</p><h2>Transfers that perform<span class="dot">.</span></h2><span class="yellow-rule"></span></header><div class="features">${features.map(([icon,title,body]) => `<article>${img(icon, '', 'feature-icon')}<h3>${title}</h3><p>${body}</p></article>`).join('')}</div></div><div class="photo-strip">${[1,2,3,4].map((n) => img(`apparel-shot${n}.png`, ['Dallas printed T-shirt','Creator wearing Support Local sweatshirt','Good Things printed transfer detail','Fort Worth printed T-shirt'][n-1])).join('')}</div><p class="same-cart">${img('shopping-cart.svg')}Transfers and blanks are optional and can be added to the same cart.</p></section>
  <section class="chapter transfer-catalog" id="all-transfers" aria-labelledby="all-transfers-title"><div class="catalog-kicker">DTF TRANSFERS</div><header><h2 id="all-transfers-title">All the ways to make it yours<span class="dot">.</span></h2><p>Choose the transfer format that fits your next project.</p></header><nav class="transfer-type-grid" aria-label="Transfer types">${transferTypes.map(([name, body]) => `<a href="${urls.transfers}" data-shop="transfers"><span>${name}</span><small>${body}</small><b aria-hidden="true">↗</b></a>`).join('')}</nav><a class="button yellow all-transfers-cta" href="${urls.transfers}" data-shop="transfers">Explore all transfers →</a></section>
  <section class="chapter apparel" id="apparel" aria-labelledby="apparel-title"><div class="editorial-nav">${brand()}<div class="editorial-words"><span>IDEAS</span><span>LOCAL</span><span>WEAR</span><span>FURTHER</span><i></i></div></div><div class="apparel-body"><div class="portrait">${img('portrait-card-standing.png','Woman wearing a white blank T-shirt and jeans')}<div class="portrait-top">SAME<br>GOOD<br>IDEAS<br>A BRIGHTER<br>DFW<span></span></div><div class="portrait-bottom">BLANKS<br>FOR A MORE<br>LOCAL TOMORROW<span></span></div></div><div class="apparel-content"><header><h2 id="apparel-title">Choose the blank<br>that fits the idea<span class="dot">.</span></h2><p>Compare materials, weight, fit, and color before you choose.</p></header>${productRow(4)}<a class="button yellow browse-blanks" href="${urls.blanks}" data-shop="blanks">Browse blank apparel →</a></div></div></section>
  <section class="chapter range" id="delivery" aria-labelledby="range-title"><header><h2 id="range-title">Is your shop in range?</h2><p>Type it in. If we cover you, you'll see the next window.</p></header>${addressForm('footer-address')}<p class="hours">${img('clock.svg')}7 days a week · 5 AM – 10 PM · Printed and driven from Dallas</p></section>
  <footer class="chapter footer"><div class="footer-columns"><div class="footer-brand"><strong>jiffy</strong><p>Shop blanks, transfers, and finished custom products in one place.</p></div><div><h3>CATALOG</h3><a href="${urls.blanks}">Blank Apparel</a><a href="${urls.transfers}">DTF Transfers</a><a href="https://www.jiffy.com/">Custom Shirts</a></div><div><h3>HELP</h3><a href="https://www.jiffy.com/trackorder">Order tracking</a><a href="https://www.jiffy.com/contact">Transfer help</a><a href="https://www.jiffy.com/contact">Contact</a></div><div><h3>ABOUT</h3><a href="https://www.jiffy.com/">About this concept</a><a href="${urls.blanks}">Product guide</a><a href="https://www.jiffy.com/contact">Support</a></div></div><div class="footer-base"><span>© 2026 Jiffy - exercise concept.</span><div><a href="https://www.jiffy.com/privacypolicy">Privacy Policy</a><a href="https://www.jiffy.com/termsofservice">Terms of Service</a></div></div></footer>`;

document.body.insertAdjacentHTML('beforeend', `<button class="help-trigger" aria-expanded="false" aria-controls="help-panel">${img('icons1.svg')}Need help?</button><aside id="help-panel" class="help-panel" hidden><h2>Need a hand?</h2><p>Get help with products, orders, and delivery.</p><a class="button navy" href="https://www.jiffy.com/contact">Contact Jiffy support →</a></aside><dialog id="delivery-choice" class="choice-dialog" aria-labelledby="choice-title"><button type="button" class="close-dialog" aria-label="Close delivery options">×</button><h2 id="choice-title">Check delivery timing or continue with standard shipping</h2><p>See what’s available at your address, or keep shopping with standard shipping.</p><div class="choice-grid"><button class="choice recommended" id="choose-local"><span class="recommendation">Recommended</span><strong>Check your delivery time</strong><span>Enter your address to see what’s available and when it can arrive.</span><b aria-hidden="true">→</b></button><a class="choice" id="choose-standard" href="${urls.transfers}"><strong>Continue with standard shipping</strong><span>Skip local delivery timing and keep shopping with standard shipping.</span><b aria-hidden="true">→</b></a></div></dialog>`);

const chapters = [...document.querySelectorAll('.chapter')]; const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)');
document.querySelector('.transfer-quality-inline header').insertAdjacentHTML('beforeend', '<p class="quality-proof-line">Best processing pipeline. Calibrated printers. Built for the close-up.</p>');
document.querySelector('.transfer-quality-inline').insertAdjacentHTML('beforeend', '<p class="quality-proof-note">Show the transfer up close, then show it pressed on apparel.</p>');
document.querySelector('#transfers .catalog-body').classList.add('transfer-entry');
document.querySelector('.all-transfers-cta').insertAdjacentHTML('beforebegin', `<div class="price-proof"><h3>Quality you can price with.</h3><p>Transfers by size, gang sheets, and everyday blanks for the next project.</p>${productRow()}</div><div class="shipping-proof">Blanks + Transfers Ship Locally For Free on Orders of $59+</div>`);
function measureChapters() { chapters.forEach((chapter, i) => { chapter.style.setProperty('--layer', i + 1); chapter.style.setProperty('--pin-top', `${Math.min(0, innerHeight - chapter.offsetHeight)}px`); }); }
const sizes = new ResizeObserver(measureChapters); chapters.forEach((chapter) => sizes.observe(chapter)); addEventListener('resize', measureChapters, { passive: true }); document.fonts.ready.then(measureChapters); measureChapters();
let addressEntered = false; const help = document.querySelector('.help-trigger'); const helpPanel = document.querySelector('#help-panel');
help.addEventListener('click', () => { const open = help.getAttribute('aria-expanded') !== 'true'; help.setAttribute('aria-expanded', String(open)); helpPanel.hidden = !open; });
const sentinel = document.createElement('div'); sentinel.className = 'hero-sentinel'; document.body.prepend(sentinel); new IntersectionObserver(([entry]) => help.classList.toggle('is-visible', entry.intersectionRatio < .2), { threshold: [.2] }).observe(sentinel);
const choice = document.querySelector('#delivery-choice');
function focusAddress() { choice.close(); window.scrollTo({ top: 0, behavior: reducedMotion.matches ? 'instant' : 'smooth' }); document.querySelector('#hero-address').focus({ preventScroll: true }); }
document.querySelectorAll('[data-shop]').forEach((link) => link.addEventListener('click', (event) => { if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; if (addressEntered) return; event.preventDefault(); document.querySelector('#choose-standard').href = link.href; choice.showModal(); }));
document.querySelector('.close-dialog').addEventListener('click', () => choice.close()); document.querySelector('#choose-local').addEventListener('click', focusAddress);
document.querySelectorAll('[data-address-form]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const address = new FormData(form).get('address').trim(); if (!address) return; addressEntered = true; document.querySelectorAll('[name="address"]').forEach((input) => { input.value = address; }); document.querySelectorAll('.address-status').forEach((status) => { status.hidden = false; status.textContent = 'Address entered. Connect the delivery service to return real availability and times.'; }); }));
const artwork = document.querySelector('#artwork'); const upload = document.querySelector('#upload-panel'); document.querySelector('#choose-file').addEventListener('click', () => { if (!addressEntered) { choice.showModal(); return; } artwork.click(); });
function showArtwork(file) { if (!file) return; const status = document.querySelector('.upload-status'); status.hidden = false; status.textContent = ['image/png','image/jpeg','application/pdf'].includes(file.type) ? `${file.name} selected. Your file stays on this device in this preview.` : 'Choose a PNG, JPG, or PDF file.'; }
artwork.addEventListener('change', () => showArtwork(artwork.files[0])); upload.addEventListener('dragover', (event) => { event.preventDefault(); upload.classList.add('dragging'); }); upload.addEventListener('dragleave', () => upload.classList.remove('dragging')); upload.addEventListener('drop', (event) => { event.preventDefault(); upload.classList.remove('dragging'); if (addressEntered) showArtwork(event.dataTransfer.files[0]); else choice.showModal(); });
